### ISSUE TITLE
Client did not get response within #1000 ms

### ISSUE THREAD

**Issue by drewdeakin** [recombee/php-api-client#15] opened 2019-07-23 10:45 UTC
Hi

I am getting the following error after installing and setting up the php-api-client via composer:

Fatal error: Uncaught Recombee\RecommApi\Exceptions\ApiTimeoutException: Client did not get response within #1000 ms in /srv/users/sandwichboard/vendor/recombee/php-api-client/src/RecommApi/Client.php:105 Stack trace: #0 /srv/users/sandwichboard/apps/sandwichboard/public/include/config.php(26): Recombee\RecommApi\Client->send(Object(Recombee\RecommApi\Requests\AddDetailView)) #1 /srv/users/sandwichboard/apps/sandwichboard/public/index.php(3): require_once('/srv/users/sand...') #2 {main} thrown in /srv/users/sandwichboard/vendor/recombee/php-api-client/src/RecommApi/Client.php on line 105

This is the code that I am trying to run (haven't changed much from what's in https://docs.recombee.com/gettingstarted.html#getting-started-catalog)
```php
  use Recombee\RecommApi\Client;
  use Recombee\RecommApi\Requests as Reqs;

  $client = new Client( $database, $key );
  $client->send(new Reqs\AddDetailView( "2c169e575644d840838e", "xyz" ) );
```

**Comment by OndraFiedler** [comment] 2019-07-23 12:06
Are you testing it from your local or some servers? Is it possible that you are on some slow connection?
You can extend the timeout for tests by setting longer timeout:
```php
$request->setTimeout(5000); // 5 seconds
```
Also the geolocation can be problematic (current default geo location of Recombee servers is west Europe) - please contact support@recombee.com for information about transferring to another Recombee geo location.

**Comment by drewdeakin** [comment] 2019-07-24 05:31
Hey @OndraFiedler, its run on a Vultr VPS based in Sydney.

Sorry, where would I put the following code?

```php
$request->setTimeout(5000); // 5 seconds
```

Ive also sent a request to support@recombee.com to see if they can transfer me to a different Recombee geo location.

**Comment by OndraFiedler** [comment] 2019-07-24 08:54
> Sorry, where would I put the following code?
```php
$request = new Reqs\AddDetailView( "2c169e575644d840838e", "xyz" );
$request->setTimeout(5000); // 5 seconds
$client->send($request);
```

**Closed by OndraFiedler** 2019-07-24 08:54 UTC

**Comment by SE-Tasneem** [comment] 2020-12-01 09:39
I have the same error 
using vpn (Netherlands)  the same request some time work fine

**Comment by OndraFiedler** [comment] 2020-12-01 09:49
As the timeouts are not related to the code of the SDK, please contact support@recombee.com.
If you are calling the Recombee API from your local computer behind a VPN, the timeouts are very likely caused by slow network connection and you might need to increase the timeouts (see above) for local development.
